CREATE TABLE IF NOT EXISTS client(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE ,
  first_name VARCHAR(30) NOT NULL ,
  last_name VARCHAR(40) NOT NULL ,
  age INT ,
  sex ENUM ('MEN','WOMEN') ,
  email VARCHAR(30) NOT NULL ,
  phone VARCHAR(13) NOT NULL ,
  login VARCHAR(50) NOT NULL ,
  password VARCHAR(50) NOT NULL ,
  photo VARCHAR(100) ,
  level ENUM ('JUNIOR','MIDDLE','SENIOR') NOT NULL ,
  role ENUM ('ATHLETE', 'COACH', 'ADMIN') NOT NULL
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS coach(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE ,
  first_name VARCHAR(30) NOT NULL ,
  last_name VARCHAR(40) NOT NULL ,
  age INT ,
  sex ENUM ('MEN','WOMEN') ,
  email VARCHAR(50) NOT NULL ,
  phone VARCHAR(13) NOT NULL ,
  login VARCHAR(50) NOT NULL ,
  password VARCHAR(50) NOT NULL ,
  photo VARCHAR(100) ,
  role ENUM ('ATHLETE', 'COACH', 'ADMIN') NOT NULL,
  sport_category ENUM ('GYM', 'FITNESS', 'RUN')
)ENGINE=INNODB;



CREATE TABLE IF NOT EXISTS sport_club(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE ,
  name VARCHAR(40) NOT NULL ,
  location VARCHAR(100) NOT NULL ,
  description VARCHAR(1000),
  coach_id BIGINT REFERENCES coach(id)
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS coach_client(
  coach_id BIGINT NOT NULL ,
  client_id BIGINT NOT NULL,
  FOREIGN KEY (coach_id) REFERENCES coach (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;




